services:
  - type: web
    name: skill-issue
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    disk:
      name: app-storage
      mountPath: /var/www/storage
      sizeGB: 1

