services:
  - type: web
    name: skill-issue
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/storage/database.sqlite
    disk:
      name: app-storage
      mountPath: /var/www/storage
      sizeGB: 1

